version: '3'
services:

  rabbit-upstream-alt:
    image: rabbitmq:3-management-alpine
    hostname: rabbit-upstream-alt
    ports:
    - "4369"
    - "5672"
    - "15672"

  rabbit-downstream-1:
    build: ./federated
    hostname: rabbit-downstream-1
    environment:
    - RABBITMQ_FEDERATED_URI=amqp://guest:guest@rabbit-upstream-alt
    ports:
    - "4369"
    - "5672"
    - "15672"

  rabbit-downstream-2:
    build: ./federated
    hostname: rabbit-downstream-2
    environment:
    - RABBITMQ_FEDERATED_URI=amqp://guest:guest@rabbit-upstream-alt
    ports:
    - "4369"
    - "5672"
    - "15672"

